# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-03-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_riot', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='mastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_riot', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
    ]
