# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-03-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_riot', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('tier', models.IntegerField(default=0)),
                ('rune_type', models.CharField(max_length=200)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=6)),
                ('honest_text', models.CharField(max_length=200)),
            ],
        ),
    ]
