# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-03-15 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rune'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='is_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
