# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-03-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rune_is_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='key',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
